---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  env:
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    OPERATOR_UNDER_TEST: ${OPERATOR_UNDER_TEST:-ansible}
  config_options:
    defaults:
      callback_whitelist: profile_tasks
    callback_profile_tasks:
      task_output_limit: 100
      sort_order: none
scenario:
  test_sequence:
    - lint
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - cleanup
    - destroy
